// Code generated by generate-typed-resources. DO NOT EDIT.
// Template: CREATE|UPDATE|DELETE

package dataengine

import (
	"context"

	"github.com/vast-data/go-vast-client/core"
)

// -----------------------------------------------------
// RESOURCE TYPE
// -----------------------------------------------------

// ElementTrigger represents a typed resource for elementtrigger operations
type ElementTrigger struct {
	*core.TypedVastResource
}

// -----------------------------------------------------
// SEARCH PARAMS
// -----------------------------------------------------

// ElementTriggerSearchParams represents the search parameters for ElementTrigger operations
type ElementTriggerSearchParams struct {

	// RawData allows passing arbitrary search parameters as key-value pairs.
	//
	// Use this field when you need query parameters that are not covered by the typed fields above.
	// This is particularly useful for:
	//   - Dynamic filter operations (e.g., "path__contains", "name__icontains")
	//   - Django-style query filters
	//   - Custom backend-specific parameters
	//
	// Example:
	//   params := &ElementTriggerSearchParams{
	//       RawData: core.Params{"path__contains": "/foo", "name__icontains": "bar"},
	//   }
	//
	// Note: You can use either the typed fields or RawData, or combine both.
	RawData core.Params `json:"-" yaml:"-"`
}

// -----------------------------------------------------
// REQUEST BODY
// -----------------------------------------------------

// TriggersElementRequestBody_Broker represents a nested type for request body
type TriggersElementRequestBody_Broker struct {
	Name                     string `json:"name,omitempty" yaml:"name,omitempty" required:"true" doc:"Broker name for external or Bucket (View) name for internal."`
	Type                     string `json:"type,omitempty" yaml:"type,omitempty" required:"true" doc:""`
	IsAccessibleToDataEngine bool   `json:"is_accessible_to_data_engine,omitempty" yaml:"is_accessible_to_data_engine,omitempty" required:"false" doc:"When true (default), the Data Engine will periodically validate that the broker is accessible. Set to false if the broker is not reachable from the Data Engine (e.g., external brokers behind firewalls)."`
	Url                      string `json:"url,omitempty" yaml:"url,omitempty" required:"false" doc:"Deprecated. The broker URL is now resolved from VMS by broker name. This field is ignored for VMS-registered brokers and only used as a legacy fallback for brokers not yet registered in VMS. It will be removed in a future release."`
}

// TriggersElementRequestBody_Config represents a nested type for request body
type TriggersElementRequestBody_Config struct {
	Events           *[]string                                     `json:"events,omitempty" yaml:"events,omitempty" required:"false" doc:"Events that trigger the element trigger. TODO: Make this field required once deprecated POST/PUT /triggers APIs are removed."`
	NameFilters      TriggersElementRequestBody_Config_NameFilters `json:"name_filters,omitempty" yaml:"name_filters,omitempty" required:"false" doc:""`
	SourceBucketName string                                        `json:"source_bucket_name,omitempty" yaml:"source_bucket_name,omitempty" required:"false" doc:"The bucket name of a VMS View. Relevant for Element Trigger. TODO: Make this field required once deprecated POST/PUT /triggers APIs are removed."`
	TagFilters       TriggersElementRequestBody_Config_TagFilters  `json:"tag_filters,omitempty" yaml:"tag_filters,omitempty" required:"false" doc:""`
}

// TriggersElementRequestBody_Config_NameFilters represents a nested type for request body
type TriggersElementRequestBody_Config_NameFilters struct {
	Prefixes *[]string `json:"prefixes,omitempty" yaml:"prefixes,omitempty" required:"false" doc:""`
	Suffixes *[]string `json:"suffixes,omitempty" yaml:"suffixes,omitempty" required:"false" doc:""`
}

// TriggersElementRequestBody_Config_TagFilters represents a nested type for request body
type TriggersElementRequestBody_Config_TagFilters struct {
	Prefixes *[]string `json:"prefixes,omitempty" yaml:"prefixes,omitempty" required:"false" doc:""`
	Suffixes *[]string `json:"suffixes,omitempty" yaml:"suffixes,omitempty" required:"false" doc:""`
}

// ElementTriggerRequestBody represents the request body for ElementTrigger operations
type ElementTriggerRequestBody struct {
	Config      TriggersElementRequestBody_Config `json:"config,omitempty" yaml:"config,omitempty" required:"true" doc:""`
	Name        string                            `json:"name,omitempty" yaml:"name,omitempty" required:"true" doc:"A name for the trigger. Must contain only lowercase letters, numbers, and hyphens."`
	Broker      TriggersElementRequestBody_Broker `json:"broker,omitempty" yaml:"broker,omitempty" required:"false" doc:""`
	Description string                            `json:"description,omitempty" yaml:"description,omitempty" required:"false" doc:"A description of the resource."`
	SourceTypes *[]string                         `json:"source_types,omitempty" yaml:"source_types,omitempty" required:"false" doc:"Source types from which we want to trigger events. Relevant for Element Trigger"`
	Tags        *[]string                         `json:"tags,omitempty" yaml:"tags,omitempty" required:"false" doc:"Custom tags for organizing and categorizing resources in the GUI."`
	TopicName   string                            `json:"topic_name,omitempty" yaml:"topic_name,omitempty" required:"false" doc:"The name of the topic in the broker. Used with broker field for automatic topic creation."`
}

// -----------------------------------------------------
// MODELS
// -----------------------------------------------------

// ElementTriggerUpsertModel represents the model returned by Create/Update operations
// Type alias to component definition: #/components/schemas/ElementTriggerResponse
type ElementTriggerUpsertModel = Component_ElementTriggerResponse

// -----------------------------------------------------
// CREATE
// -----------------------------------------------------

// Create creates a new elementtrigger with typed request/response
// summary: Create a new Element Trigger
func (r *ElementTrigger) Create(req *ElementTriggerRequestBody) (*ElementTriggerUpsertModel, error) {
	return r.CreateWithContext(r.Untyped.GetCtx(), req)
}

// CreateWithContext creates a new elementtrigger with typed request/response using provided context
// summary: Create a new Element Trigger
func (r *ElementTrigger) CreateWithContext(ctx context.Context, req *ElementTriggerRequestBody) (*ElementTriggerUpsertModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].CreateWithContext(ctx, params)
	if err != nil {
		return nil, err
	}

	var response ElementTriggerUpsertModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// -----------------------------------------------------
// UPDATE
// -----------------------------------------------------

// Update updates an existing elementtrigger with typed request/response
// summary: Partially Update Element Trigger by ID
func (r *ElementTrigger) Update(id any, req *ElementTriggerRequestBody) (*ElementTriggerUpsertModel, error) {
	return r.UpdateWithContext(r.Untyped.GetCtx(), id, req)
}

// UpdateWithContext updates an existing elementtrigger with typed request/response using provided context
// summary: Partially Update Element Trigger by ID
func (r *ElementTrigger) UpdateWithContext(ctx context.Context, id any, req *ElementTriggerRequestBody) (*ElementTriggerUpsertModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].UpdateWithContext(ctx, id, params)
	if err != nil {
		return nil, err
	}

	var response ElementTriggerUpsertModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// -----------------------------------------------------
// DELETE
// -----------------------------------------------------

// Delete deletes a elementtrigger with search parameters
func (r *ElementTrigger) Delete(req *ElementTriggerSearchParams) error {
	return r.DeleteWithContext(r.Untyped.GetCtx(), req)
}

// DeleteWithContext deletes a elementtrigger with search parameters using provided context
func (r *ElementTrigger) DeleteWithContext(ctx context.Context, req *ElementTriggerSearchParams) error {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return err
	}
	_, err = r.Untyped.GetResourceMap()[r.GetResourceType()].DeleteWithContext(ctx, params)
	if err != nil {
		return err
	}
	return nil
}

// DeleteById deletes a elementtrigger by ID
func (r *ElementTrigger) DeleteById(id any) error {
	return r.DeleteByIdWithContext(r.Untyped.GetCtx(), id)
}

// DeleteByIdWithContext deletes a elementtrigger by ID using provided context
func (r *ElementTrigger) DeleteByIdWithContext(ctx context.Context, id any) error {
	_, err := r.Untyped.GetResourceMap()[r.GetResourceType()].DeleteByIdWithContext(ctx, id)
	if err != nil {
		return err
	}
	return nil
}
