// Code generated by generate-typed-resources. DO NOT EDIT.
// Template: CREATE|LIST|READ|UPDATE|DELETE

package dataengine

import (
	"context"
	"fmt"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
	"github.com/vast-data/go-vast-client/resources/typed/expr"
)

// -----------------------------------------------------
// RESOURCE TYPE
// -----------------------------------------------------

// Pipeline represents a typed resource for pipeline operations
type Pipeline struct {
	*core.TypedVastResource
}

// -----------------------------------------------------
// SEARCH PARAMS
// -----------------------------------------------------

// PipelineSearchParams represents the search parameters for Pipeline operations
type PipelineSearchParams struct {
	CreatedAfter         expr.IntField `json:"created_after,omitempty" yaml:"created_after,omitempty" required:"false" doc:"Filter pipelines created after this timestamp (microseconds since epoch)"`
	CreatedBefore        expr.IntField `json:"created_before,omitempty" yaml:"created_before,omitempty" required:"false" doc:"Filter pipelines created before this timestamp (microseconds since epoch)"`
	Guid                 expr.StrField `json:"guid,omitempty" yaml:"guid,omitempty" required:"false" doc:"Filter by pipeline GUID"`
	KubernetesClusterVrn expr.StrField `json:"kubernetes_cluster_vrn,omitempty" yaml:"kubernetes_cluster_vrn,omitempty" required:"false" doc:"Filter by Kubernetes cluster VRN"`
	LastRevisionNumber   expr.IntField `json:"last_revision_number,omitempty" yaml:"last_revision_number,omitempty" required:"false" doc:"Filter by last revision number"`
	Name                 expr.StrField `json:"name,omitempty" yaml:"name,omitempty" required:"false" doc:"Filter by pipeline name"`
	Namespace            expr.StrField `json:"namespace,omitempty" yaml:"namespace,omitempty" required:"false" doc:"Filter by namespace"`
	OrderBy              expr.StrField `json:"order_by,omitempty" yaml:"order_by,omitempty" required:"false" doc:"Sort order - ascending (asc) or descending (desc)"`
	OwnerName            expr.StrField `json:"owner_name,omitempty" yaml:"owner_name,omitempty" required:"false" doc:"Filter by owner name"`
	Status               expr.StrField `json:"status,omitempty" yaml:"status,omitempty" required:"false" doc:"Filter by pipeline status"`
	UpdatedAfter         expr.IntField `json:"updated_after,omitempty" yaml:"updated_after,omitempty" required:"false" doc:"Filter pipelines updated after this timestamp (microseconds since epoch)"`
	UpdatedBefore        expr.IntField `json:"updated_before,omitempty" yaml:"updated_before,omitempty" required:"false" doc:"Filter pipelines updated before this timestamp (microseconds since epoch)"`
	Vrn                  expr.StrField `json:"vrn,omitempty" yaml:"vrn,omitempty" required:"false" doc:"Filter by pipeline VRN"`

	// RawData allows passing arbitrary search parameters as key-value pairs.
	//
	// Use this field when you need query parameters that are not covered by the typed fields above.
	// This is particularly useful for:
	//   - Dynamic filter operations (e.g., "path__contains", "name__icontains")
	//   - Django-style query filters
	//   - Custom backend-specific parameters
	//
	// Example:
	//   params := &PipelineSearchParams{
	//       RawData: core.Params{"path__contains": "/foo", "name__icontains": "bar"},
	//   }
	//
	// Note: You can use either the typed fields or RawData, or combine both.
	RawData core.Params `json:"-" yaml:"-"`
}

// -----------------------------------------------------
// REQUEST BODY
// -----------------------------------------------------

// PipelineRequestBody_Manifest represents a nested type for request body
type PipelineRequestBody_Manifest struct {
	Config              string                                                  `json:"config,omitempty" yaml:"config,omitempty" required:"false" doc:""`
	FunctionDeployments *[]PipelineRequestBody_Manifest_FunctionDeploymentsItem `json:"function_deployments,omitempty" yaml:"function_deployments,omitempty" required:"false" doc:""`
	Links               *[]PipelineRequestBody_Manifest_LinksItem               `json:"links,omitempty" yaml:"links,omitempty" required:"false" doc:"Links which define the calling graph of functions in a pipeline. | Each of the sources at the source array triggers all function deployments in the destination array | if all the labels in the conditional_trigger_labels array are set to the specified values. | The label values are set by the source function handler using the context.set_trigger_labels() method."`
	Triggers            *[]PipelineRequestBody_Manifest_TriggersItem            `json:"triggers,omitempty" yaml:"triggers,omitempty" required:"false" doc:""`
}

// PipelineRequestBody_Manifest_FunctionDeploymentsItem represents a nested type for request body
type PipelineRequestBody_Manifest_FunctionDeploymentsItem struct {
	FunctionVrn string                                                         `json:"function_vrn,omitempty" yaml:"function_vrn,omitempty" required:"true" doc:"A logical path for resource grouping and policy assignment. The structure of the logical path is: vast:dataengine:<resource type>:<custom structure per type> where resource type is one of: triggers / functions / pipelines / topics / kubernetes-clusters / container-registries / mtls-authentication-credentials."`
	Name        string                                                         `json:"name,omitempty" yaml:"name,omitempty" required:"true" doc:""`
	Config      string                                                         `json:"config,omitempty" yaml:"config,omitempty" required:"false" doc:""`
	Resources   PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources `json:"resources,omitempty" yaml:"resources,omitempty" required:"false" doc:""`
	Revision    int64                                                          `json:"revision,omitempty" yaml:"revision,omitempty" required:"false" doc:""`
}

// PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources represents a nested type for request body
type PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources struct {
	Autoscaling                          PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling `json:"autoscaling,omitempty" yaml:"autoscaling,omitempty" required:"false" doc:"Autoscaling configuration for the function deployment. Defines how the function scales based on incoming requests or resource utilization. Three autoscaling metrics are supported: - concurrency: Scale based on concurrent requests per instance (default, supports scale-to-zero) - rps: Scale based on requests per second per instance (supports scale-to-zero) - resource: Scale based on CPU or memory utilization (does not support scale-to-zero) Only one of 'concurrency', 'rps', or 'resource' should be provided, matching the 'metric' field."`
	AutoscalingConcurrencyOverloadFactor string                                                                     `json:"autoscaling_concurrency_overload_factor,omitempty" yaml:"autoscaling_concurrency_overload_factor,omitempty" required:"false" doc:"Deprecated: Use 'autoscaling' field instead with type='kpa_concurrency'. Autoscaling concurrency overload factor (> 0.0). Determines when to scale based on concurrency overload beyond current processing capacity. When concurrency exceeds (capacity * (1 + overload_factor)), new function instances are created. For backward compatibility, if this field is set and 'autoscaling' is not provided, concurrency metric autoscaling will be used with target_utilization_percentage calculated from this value. Default: \"0.05\" (5% overload tolerance)"`
	AutoscalingRpsFactor                 int64                                                                      `json:"autoscaling_rps_factor,omitempty" yaml:"autoscaling_rps_factor,omitempty" required:"false" doc:"Deprecated: This field is no longer used and will be removed in a future version. It is ignored if provided."`
	MaxConcurrency                       int64                                                                      `json:"max_concurrency,omitempty" yaml:"max_concurrency,omitempty" required:"false" doc:"10"`
	MaxConcurrentRequestsLimit           int64                                                                      `json:"max_concurrent_requests_limit,omitempty" yaml:"max_concurrent_requests_limit,omitempty" required:"false" doc:"Maximum number of concurrent requests the function can handle per instance. This represents how many requests can be processed simultaneously (in-flight) by a single function instance. Maps to Knative 'spec.containerConcurrency'. If omitted, the value is computed at deploy time as 'max(num_workers, batch_max_size)' (defaults: 'max(20, 1) = 20'). This ensures the queue-proxy enforces backpressure per pod so the autoscaler can scale out instead of all traffic piling on a single pod. Set explicitly to '0' for unlimited per-pod concurrency (queue-proxy does not throttle). Use with caution: with '0' the autoscaler cannot observe queue pressure and may keep traffic on a single instance. Setting this value below the actual function capacity will hurt performance. Set ONLY if you know an upper bound for the capacity; this applies backpressure on a loaded function instance and waits for autoscale instead of queueing requests, which can tune performance and avoid timed-out requests in the queue and retries. WARNING: If autoscaling is configured with concurrency metric (or the deprecated autoscaling_concurrency_overload_factor), this value must be GREATER THAN OR EQUAL TO the target value. Otherwise the effective target for autoscaling will be the MINIMUM of this value and the target value."`
	MaxCpu                               string                                                                     `json:"max_cpu,omitempty" yaml:"max_cpu,omitempty" required:"false" doc:""`
	MaxMemory                            string                                                                     `json:"max_memory,omitempty" yaml:"max_memory,omitempty" required:"false" doc:""`
	MinConcurrency                       int64                                                                      `json:"min_concurrency,omitempty" yaml:"min_concurrency,omitempty" required:"false" doc:""`
	MinCpu                               string                                                                     `json:"min_cpu,omitempty" yaml:"min_cpu,omitempty" required:"false" doc:""`
	MinMemory                            string                                                                     `json:"min_memory,omitempty" yaml:"min_memory,omitempty" required:"false" doc:""`
	NumWorkers                           int64                                                                      `json:"num_workers,omitempty" yaml:"num_workers,omitempty" required:"false" doc:"Number of worker threads per function instance. When event batching is enabled, the effective concurrency per instance is num_workers * batch_max_size, since each worker processes one batch at a time. Default: 20 (matches the default Python runtime worker threads) Maximum: 100"`
	Storage                              string                                                                     `json:"storage,omitempty" yaml:"storage,omitempty" required:"false" doc:""`
	Timeout                              int64                                                                      `json:"timeout,omitempty" yaml:"timeout,omitempty" required:"false" doc:"Timeout in seconds for the function deployment."`
}

// PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling represents a nested type for request body
type PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling struct {
	Metric      string                                                                              `json:"metric,omitempty" yaml:"metric,omitempty" required:"true" doc:"The metric used for autoscaling decisions. Determines which configuration object should be provided: - concurrency: Provide 'concurrency' configuration object - rps: Provide 'rps' configuration object - resource: Provide 'resource' configuration object"`
	Concurrency string                                                                              `json:"concurrency,omitempty" yaml:"concurrency,omitempty" required:"false" doc:"Autoscaling configuration based on concurrent requests metric. Extends RequestAutoscalingConfig with concurrency-specific options."`
	Resource    PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling_Resource `json:"resource,omitempty" yaml:"resource,omitempty" required:"false" doc:"Autoscaling configuration based on resource utilization (CPU or memory). Note: Resource-based autoscaling does not support scale-to-zero. Use concurrency or rps metrics if scale-to-zero is required."`
	Rps         PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling_Rps      `json:"rps,omitempty" yaml:"rps,omitempty" required:"false" doc:"Common autoscaling configuration for request-based metrics (concurrency and RPS). This configuration supports scale-to-zero when there is no traffic."`
}

// PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling_Resource represents a nested type for request body
type PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling_Resource struct {
	ResourceAutoscalingType string `json:"resource_autoscaling_type,omitempty" yaml:"resource_autoscaling_type,omitempty" required:"true" doc:"The resource type to use for autoscaling: - cpu: Scale based on CPU utilization percentage - memory: Scale based on memory utilization percentage"`
	Target                  int64  `json:"target,omitempty" yaml:"target,omitempty" required:"true" doc:"Target value for the selected resource. For CPU, this is the target utilization percentage (e.g., 80 means 80% of CPU request). Note: The Knative documentation at https://knative.dev/docs/serving/autoscaling/autoscaling-metrics/ incorrectly states this is in millicores, but testing and Knative source code confirm it's a percentage. For memory, this is in Mi (e.g., 200 means 200Mi). The HPA will scale when actual usage exceeds this target."`
	StableWindowSeconds     int64  `json:"stable_window_seconds,omitempty" yaml:"stable_window_seconds,omitempty" required:"false" doc:"Time window in seconds for stable autoscaling decisions (6 to 3600). This controls the HPA stabilization window for scale-down decisions. Larger values result in more smoothing and slower scale-down. Default: not set (uses Kubernetes HPA default of 300s)"`
}

// PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling_Rps represents a nested type for request body
type PipelineRequestBody_Manifest_FunctionDeploymentsItem_Resources_Autoscaling_Rps struct {
	BurstThresholdPercentage    int64 `json:"burst_threshold_percentage,omitempty" yaml:"burst_threshold_percentage,omitempty" required:"false" doc:"Burst mode threshold as a percentage of current capacity (110-1000). Burst mode is triggered when traffic exceeds this percentage of what current instances can handle. For example, 200 means burst mode starts when traffic is 2x current capacity."`
	BurstWindowPercentage       int64 `json:"burst_window_percentage,omitempty" yaml:"burst_window_percentage,omitempty" required:"false" doc:"Burst detection window as a percentage of stable window (1-100). Defines the shorter time window used to detect traffic bursts. Lower values make burst detection more sensitive."`
	ScaleDownDelaySeconds       int64 `json:"scale_down_delay_seconds,omitempty" yaml:"scale_down_delay_seconds,omitempty" required:"false" doc:"Delay in seconds before scaling down after load decreases. Helps prevent thrashing during fluctuating traffic."`
	ScaleToZeroDelaySeconds     int64 `json:"scale_to_zero_delay_seconds,omitempty" yaml:"scale_to_zero_delay_seconds,omitempty" required:"false" doc:"Minimum time in seconds to retain the last instance before scaling to zero. The instance is kept for at least this duration after the autoscaler decides to scale to zero."`
	StableWindowSeconds         int64 `json:"stable_window_seconds,omitempty" yaml:"stable_window_seconds,omitempty" required:"false" doc:"Time window in seconds for stable autoscaling decisions (6 to 3600). Larger values result in more smoothing. When scaling to zero, the last instance is only removed after no traffic for the entire duration of this window."`
	Target                      int64 `json:"target,omitempty" yaml:"target,omitempty" required:"false" doc:"Target value per instance. The autoscaler will try to maintain this level per instance. - For concurrency metric: target number of concurrent requests (default: 20, which matches the default number of worker threads in non-asyncio Python functions) - For RPS metric: target requests per second"`
	TargetUtilizationPercentage int64 `json:"target_utilization_percentage,omitempty" yaml:"target_utilization_percentage,omitempty" required:"false" doc:"Target utilization percentage (1-100). Specifies what percentage of the target should actually be targeted by the autoscaler. This causes the autoscaler to scale up before the target is reached. For example, with target=10 and target_utilization_percentage=70, the autoscaler will create a new instance when average metric value reaches 7."`
}

// PipelineRequestBody_Manifest_LinksItem represents a nested type for request body
type PipelineRequestBody_Manifest_LinksItem struct {
	Destination              *[]string                                                              `json:"destination,omitempty" yaml:"destination,omitempty" required:"true" doc:""`
	Source                   *[]string                                                              `json:"source,omitempty" yaml:"source,omitempty" required:"true" doc:""`
	ConditionalTriggerLabels *[]PipelineRequestBody_Manifest_LinksItem_ConditionalTriggerLabelsItem `json:"conditional_trigger_labels,omitempty" yaml:"conditional_trigger_labels,omitempty" required:"false" doc:"Conditional trigger labels for the link. These are used to conditionally trigger the link. | All labels must be set to the specified values to trigger the link (i.e. AND operation between labels) | Labels names must be up to 15 lowercase characters or digits, must start with a letter"`
	Config                   PipelineRequestBody_Manifest_LinksItem_Config                          `json:"config,omitempty" yaml:"config,omitempty" required:"false" doc:""`
	Topic                    string                                                                 `json:"topic,omitempty" yaml:"topic,omitempty" required:"false" doc:"A logical path for resource grouping and policy assignment. The structure of the logical path is: vast:dataengine:<resource type>:<custom structure per type> where resource type is one of: triggers / functions / pipelines / topics / kubernetes-clusters / container-registries / mtls-authentication-credentials."`
}

// PipelineRequestBody_Manifest_LinksItem_ConditionalTriggerLabelsItem represents a nested type for request body
type PipelineRequestBody_Manifest_LinksItem_ConditionalTriggerLabelsItem struct {
	TriggerLabelName  string `json:"triggerLabelName,omitempty" yaml:"triggerLabelName,omitempty" required:"true" doc:""`
	TriggerLabelValue string `json:"triggerLabelValue,omitempty" yaml:"triggerLabelValue,omitempty" required:"true" doc:""`
}

// PipelineRequestBody_Manifest_LinksItem_Config represents a nested type for request body
type PipelineRequestBody_Manifest_LinksItem_Config struct {
	EventsOrder string `json:"events_order,omitempty" yaml:"events_order,omitempty" required:"false" doc:"Ordering of events for the trigger."`
	Retries     int64  `json:"retries,omitempty" yaml:"retries,omitempty" required:"false" doc:"Number of retries for the trigger."`
}

// PipelineRequestBody_Manifest_TriggersItem represents a nested type for request body
type PipelineRequestBody_Manifest_TriggersItem struct {
	Name string `json:"name,omitempty" yaml:"name,omitempty" required:"true" doc:""`
	Vrn  string `json:"vrn,omitempty" yaml:"vrn,omitempty" required:"true" doc:"A logical path for resource grouping and policy assignment. The structure of the logical path is: vast:dataengine:<resource type>:<custom structure per type> where resource type is one of: triggers / functions / pipelines / topics / kubernetes-clusters / container-registries / mtls-authentication-credentials."`
}

// PipelineRequestBody represents the request body for Pipeline operations
type PipelineRequestBody struct {
	Name                 string                       `json:"name,omitempty" yaml:"name,omitempty" required:"true" doc:"A name for the resource."`
	Description          string                       `json:"description,omitempty" yaml:"description,omitempty" required:"false" doc:"A description of the resource."`
	KubernetesClusterVrn string                       `json:"kubernetes_cluster_vrn,omitempty" yaml:"kubernetes_cluster_vrn,omitempty" required:"false" doc:"A logical path for resource grouping and policy assignment. The structure of the logical path is: vast:dataengine:<resource type>:<custom structure per type> where resource type is one of: triggers / functions / pipelines / topics / kubernetes-clusters / container-registries / mtls-authentication-credentials."`
	Manifest             PipelineRequestBody_Manifest `json:"manifest,omitempty" yaml:"manifest,omitempty" required:"false" doc:""`
	Namespace            string                       `json:"namespace,omitempty" yaml:"namespace,omitempty" required:"false" doc:"The namespace in the kubernetes cluster"`
	Tags                 *[]string                    `json:"tags,omitempty" yaml:"tags,omitempty" required:"false" doc:"Custom tags for organizing and categorizing resources in the GUI."`
}

// -----------------------------------------------------
// MODELS
// -----------------------------------------------------

// PipelineDetailsModel represents the detailed model returned by GET/List operations
// Type alias to component definition: #/components/schemas/Pipeline
type PipelineDetailsModel = Component_Pipeline

// PipelineUpsertModel represents the model returned by Create/Update operations
// Type alias to component definition: #/components/schemas/Pipeline
type PipelineUpsertModel = Component_Pipeline

// -----------------------------------------------------
// LIST
// -----------------------------------------------------

// List retrieves multiple pipelines with typed request/response
// summary: List all Pipelines
func (r *Pipeline) List(req *PipelineSearchParams) ([]*PipelineDetailsModel, error) {
	return r.ListWithContext(r.Untyped.GetCtx(), req)
}

// ListWithContext retrieves multiple pipelines with typed request/response using provided context
// summary: List all Pipelines
func (r *Pipeline) ListWithContext(ctx context.Context, req *PipelineSearchParams) ([]*PipelineDetailsModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	recordSet, err := r.Untyped.GetResourceMap()[r.GetResourceType()].ListWithContext(ctx, params)
	if err != nil {
		return nil, err
	}

	var response []*PipelineDetailsModel
	if err := recordSet.Fill(&response); err != nil {
		return nil, err
	}

	return response, nil
}

// Get retrieves a single pipeline with typed request/response
// summary: List all Pipelines
func (r *Pipeline) Get(req *PipelineSearchParams) (*PipelineDetailsModel, error) {
	return r.GetWithContext(r.Untyped.GetCtx(), req)
}

// GetWithContext retrieves a single pipeline with typed request/response using provided context
// summary: List all Pipelines
func (r *Pipeline) GetWithContext(ctx context.Context, req *PipelineSearchParams) (*PipelineDetailsModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].GetWithContext(ctx, params)
	if err != nil {
		return nil, err
	}

	var response PipelineDetailsModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// -----------------------------------------------------
// READ
// -----------------------------------------------------

// GetById retrieves a single pipeline by ID
// summary: Get Pipeline by ID
func (r *Pipeline) GetById(id any) (*PipelineDetailsModel, error) {
	return r.GetByIdWithContext(r.Untyped.GetCtx(), id)
}

// GetByIdWithContext retrieves a single pipeline by ID using provided context
// summary: Get Pipeline by ID
func (r *Pipeline) GetByIdWithContext(ctx context.Context, id any) (*PipelineDetailsModel, error) {
	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].GetByIdWithContext(ctx, id)
	if err != nil {
		return nil, err
	}

	var response PipelineDetailsModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// -----------------------------------------------------
// CREATE
// -----------------------------------------------------

// Create creates a new pipeline with typed request/response
// summary: Create a new Pipeline
func (r *Pipeline) Create(req *PipelineRequestBody) (*PipelineUpsertModel, error) {
	return r.CreateWithContext(r.Untyped.GetCtx(), req)
}

// CreateWithContext creates a new pipeline with typed request/response using provided context
// summary: Create a new Pipeline
func (r *Pipeline) CreateWithContext(ctx context.Context, req *PipelineRequestBody) (*PipelineUpsertModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].CreateWithContext(ctx, params)
	if err != nil {
		return nil, err
	}

	var response PipelineUpsertModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// -----------------------------------------------------
// UPDATE
// -----------------------------------------------------

// Update updates an existing pipeline with typed request/response
// summary: Partially Update Pipeline by ID
func (r *Pipeline) Update(id any, req *PipelineRequestBody) (*PipelineUpsertModel, error) {
	return r.UpdateWithContext(r.Untyped.GetCtx(), id, req)
}

// UpdateWithContext updates an existing pipeline with typed request/response using provided context
// summary: Partially Update Pipeline by ID
func (r *Pipeline) UpdateWithContext(ctx context.Context, id any, req *PipelineRequestBody) (*PipelineUpsertModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].UpdateWithContext(ctx, id, params)
	if err != nil {
		return nil, err
	}

	var response PipelineUpsertModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// -----------------------------------------------------
// DELETE
// -----------------------------------------------------

// Delete deletes a pipeline with search parameters
func (r *Pipeline) Delete(req *PipelineSearchParams) error {
	return r.DeleteWithContext(r.Untyped.GetCtx(), req)
}

// DeleteWithContext deletes a pipeline with search parameters using provided context
func (r *Pipeline) DeleteWithContext(ctx context.Context, req *PipelineSearchParams) error {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return err
	}
	_, err = r.Untyped.GetResourceMap()[r.GetResourceType()].DeleteWithContext(ctx, params)
	if err != nil {
		return err
	}
	return nil
}

// DeleteById deletes a pipeline by ID
// summary: Delete Pipeline by ID
func (r *Pipeline) DeleteById(id any) error {
	return r.DeleteByIdWithContext(r.Untyped.GetCtx(), id)
}

// DeleteByIdWithContext deletes a pipeline by ID using provided context
// summary: Delete Pipeline by ID
func (r *Pipeline) DeleteByIdWithContext(ctx context.Context, id any) error {
	_, err := r.Untyped.GetResourceMap()[r.GetResourceType()].DeleteByIdWithContext(ctx, id)
	if err != nil {
		return err
	}
	return nil
}

// -----------------------------------------------------
// ENSURE
// -----------------------------------------------------

// Ensure ensures a pipeline exists with typed response
func (r *Pipeline) Ensure(searchParams *PipelineSearchParams, body *PipelineRequestBody) (*PipelineUpsertModel, error) {
	return r.EnsureWithContext(r.Untyped.GetCtx(), searchParams, body)
}

// EnsureWithContext ensures a pipeline exists with typed response using provided context
func (r *Pipeline) EnsureWithContext(ctx context.Context, searchParams *PipelineSearchParams, body *PipelineRequestBody) (*PipelineUpsertModel, error) {
	searchParamsConverted, err := core.NewParamsFromStruct(searchParams)
	if err != nil {
		return nil, err
	}
	bodyConverted, err := core.NewParamsFromStruct(body)
	if err != nil {
		return nil, err
	}

	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].EnsureWithContext(ctx, searchParamsConverted, bodyConverted)
	if err != nil {
		return nil, err
	}

	var response PipelineUpsertModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// Exists checks if a pipeline exists
func (r *Pipeline) Exists(req *PipelineSearchParams) (bool, error) {
	return r.ExistsWithContext(r.Untyped.GetCtx(), req)
}

// ExistsWithContext checks if a pipeline exists using provided context
func (r *Pipeline) ExistsWithContext(ctx context.Context, req *PipelineSearchParams) (bool, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return false, err
	}
	return r.Untyped.GetResourceMap()[r.GetResourceType()].ExistsWithContext(ctx, params)
}

// MustExists checks if a pipeline exists and panics if not
func (r *Pipeline) MustExists(req *PipelineSearchParams) bool {
	return r.MustExistsWithContext(r.Untyped.GetCtx(), req)
}

// MustExistsWithContext checks if a pipeline exists and panics if not using provided context
func (r *Pipeline) MustExistsWithContext(ctx context.Context, req *PipelineSearchParams) bool {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		panic(err)
	}
	return r.Untyped.GetResourceMap()[r.GetResourceType()].MustExistsWithContext(ctx, params)
}

// -----------------------------------------------------
// EXTRA METHODS
// -----------------------------------------------------

// PipelineBulkDeleteModel_ResultsItem represents a nested type for Pipeline extra method response
type PipelineBulkDeleteModel_ResultsItem struct {
	Guid    string `json:"guid,omitempty" yaml:"guid,omitempty" required:"true" doc:"The GUID that was attempted to be deleted"`
	Success bool   `json:"success,omitempty" yaml:"success,omitempty" required:"true" doc:"Whether the deletion was successful"`
	Error   string `json:"error,omitempty" yaml:"error,omitempty" required:"false" doc:"Error message if deletion failed"`
}

// PipelineBulkPromoteModel_ResultsItem represents a nested type for Pipeline extra method response
type PipelineBulkPromoteModel_ResultsItem struct {
	PipelineGuid string `json:"pipeline_guid,omitempty" yaml:"pipeline_guid,omitempty" required:"true" doc:"The pipeline GUID that was attempted to be promoted"`
	Status       string `json:"status,omitempty" yaml:"status,omitempty" required:"true" doc:"Whether the promotion started successfully"`
	Error        string `json:"error,omitempty" yaml:"error,omitempty" required:"false" doc:"Error message if promotion failed to start"`
	StackGuid    string `json:"stack_guid,omitempty" yaml:"stack_guid,omitempty" required:"false" doc:"The resolved stack GUID for this pipeline"`
}

// PipelineBulkDelete_POST_Body represents the request body for PipelineBulkDelete
type PipelineBulkDelete_POST_Body struct {
	Guids *[]string `json:"guids,omitempty" yaml:"guids,omitempty" required:"true" doc:"List of GUIDs to delete"`
}

// PipelineBulkDelete_POST_Model represents the response model for PipelineBulkDelete
type PipelineBulkDelete_POST_Model struct {
	Results *[]PipelineBulkDeleteModel_ResultsItem `json:"results,omitempty" yaml:"results,omitempty" required:"true" doc:"Results for each GUID deletion attempt"`
}

// PipelineBulkDeleteWithContext_POST
// method: POST
// url: /pipelines/bulk-delete/
// summary: Bulk delete Pipelines
func (r *Pipeline) PipelineBulkDeleteWithContext_POST(ctx context.Context, body *PipelineBulkDelete_POST_Body) (*PipelineBulkDelete_POST_Model, error) {
	resourcePath := "/pipelines/bulk-delete/"

	var reqParams core.Params
	reqBody, err := core.NewParamsFromStruct(body)
	if err != nil {
		return nil, err
	}

	record, err := core.Request[core.Record](ctx, r.Untyped.GetResourceMap()[r.GetResourceType()], http.MethodPost, resourcePath, reqParams, reqBody)
	if err != nil {
		return nil, err
	}

	var response PipelineBulkDelete_POST_Model
	if err := record.Fill(&response); err != nil {
		return nil, err
	}
	return &response, nil

}

// PipelineBulkDelete_POST
// method: POST
// url: /pipelines/bulk-delete/
// summary: Bulk delete Pipelines
func (r *Pipeline) PipelineBulkDelete_POST(body *PipelineBulkDelete_POST_Body) (*PipelineBulkDelete_POST_Model, error) {
	return r.PipelineBulkDeleteWithContext_POST(r.Untyped.GetCtx(), body)
}

// PipelineBulkPromote_POST_Model represents the response model for PipelineBulkPromote
type PipelineBulkPromote_POST_Model struct {
	Failed  int64                                   `json:"failed,omitempty" yaml:"failed,omitempty" required:"true" doc:"Number of pipelines that failed validation"`
	Results *[]PipelineBulkPromoteModel_ResultsItem `json:"results,omitempty" yaml:"results,omitempty" required:"true" doc:"Results for each pipeline GUID"`
	Started int64                                   `json:"started,omitempty" yaml:"started,omitempty" required:"true" doc:"Number of pipelines that started promoting"`
	Total   int64                                   `json:"total,omitempty" yaml:"total,omitempty" required:"true" doc:"Total number of pipelines requested"`
}

// PipelineBulkPromoteWithContext_POST
// method: POST
// url: /pipelines/bulk-promote/
// summary: Bulk promote pipelines' auto-generated stacks
//
// Parameters:
//   - pipelineGuids (body): List of pipeline GUIDs to promote
func (r *Pipeline) PipelineBulkPromoteWithContext_POST(ctx context.Context, pipelineGuids string) (*PipelineBulkPromote_POST_Model, error) {
	resourcePath := "/pipelines/bulk-promote/"

	var reqParams core.Params
	reqBody := core.Params{}
	reqBody["pipeline_guids"] = pipelineGuids

	record, err := core.Request[core.Record](ctx, r.Untyped.GetResourceMap()[r.GetResourceType()], http.MethodPost, resourcePath, reqParams, reqBody)
	if err != nil {
		return nil, err
	}

	var response PipelineBulkPromote_POST_Model
	if err := record.Fill(&response); err != nil {
		return nil, err
	}
	return &response, nil

}

// PipelineBulkPromote_POST
// method: POST
// url: /pipelines/bulk-promote/
// summary: Bulk promote pipelines' auto-generated stacks
//
// Parameters:
//   - pipelineGuids (body): List of pipeline GUIDs to promote
func (r *Pipeline) PipelineBulkPromote_POST(pipelineGuids string) (*PipelineBulkPromote_POST_Model, error) {
	return r.PipelineBulkPromoteWithContext_POST(r.Untyped.GetCtx(), pipelineGuids)
}

// PipelineGuidsWithContext_GET
// method: GET
// url: /pipelines/guids/
// summary: Get list of pipeline GUIDs
func (r *Pipeline) PipelineGuidsWithContext_GET(ctx context.Context) ([]string, error) {
	resourcePath := "/pipelines/guids/"

	var reqParams core.Params
	var reqBody core.Params

	record, err := core.Request[core.RecordSet](ctx, r.Untyped.GetResourceMap()[r.GetResourceType()], http.MethodGet, resourcePath, reqParams, reqBody)
	if err != nil {
		return nil, err
	}
	// Convert RecordSet ([]core.Record) to typed array ([]string)
	result := make([]string, len(record))
	for i, item := range record {
		if err := item.Fill(&result[i]); err != nil {
			return nil, fmt.Errorf("failed to unmarshal array item %d: %w", i, err)
		}
	}
	return result, nil

}

// PipelineGuids_GET
// method: GET
// url: /pipelines/guids/
// summary: Get list of pipeline GUIDs
func (r *Pipeline) PipelineGuids_GET() ([]string, error) {
	return r.PipelineGuidsWithContext_GET(r.Untyped.GetCtx())
}

// PipelinePromoteWithContext_POST
// method: POST
// url: /pipelines/{guid}/promote/
// summary: Promote a pipeline's auto-generated stack
func (r *Pipeline) PipelinePromoteWithContext_POST(ctx context.Context, id any) error {
	resourcePath := core.BuildResourcePathWithID("pipelines", id, "promote")

	var reqParams core.Params
	var reqBody core.Params

	_, err := core.Request[core.Record](ctx, r.Untyped.GetResourceMap()[r.GetResourceType()], http.MethodPost, resourcePath, reqParams, reqBody)
	return err

}

// PipelinePromote_POST
// method: POST
// url: /pipelines/{guid}/promote/
// summary: Promote a pipeline's auto-generated stack
func (r *Pipeline) PipelinePromote_POST(id any) error {
	return r.PipelinePromoteWithContext_POST(r.Untyped.GetCtx(), id)
}

// -----------------------------------------------------
// GENERATION ISSUES
// -----------------------------------------------------
//   - Extra method POST /pipelines/is-promote-supported/ skipped: POST /pipelines/is-promote-supported/ - Response is a map-like object (additionalProperties: object). Typed methods do not support map return types
