// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// BigCatalogConfigColumnsWithContext_GET
// method: GET
// url: /bigcatalogconfig/columns/
// summary: Return VAST Catalog columns
func (b *BigCatalogConfig) BigCatalogConfigColumnsWithContext_GET(ctx context.Context, params core.Params) (core.RecordSet, error) {
	resourcePath := "/bigcatalogconfig/columns/"
	result, err := core.Request[core.RecordSet](ctx, b, http.MethodGet, resourcePath, params, nil)
	if err != nil {
		return nil, err
	}
	return result, nil

}

// BigCatalogConfigColumns_GET
// method: GET
// url: /bigcatalogconfig/columns/
// summary: Return VAST Catalog columns
func (b *BigCatalogConfig) BigCatalogConfigColumns_GET(params core.Params) (core.RecordSet, error) {
	return b.BigCatalogConfigColumnsWithContext_GET(b.Rest.GetCtx(), params)
}

// BigCatalogConfigQueryDataWithContext_GET
// method: GET
// url: /bigcatalogconfig/query_data/
// summary: Queries data based on provided params
func (b *BigCatalogConfig) BigCatalogConfigQueryDataWithContext_GET(ctx context.Context, params core.Params) (core.Record, error) {
	resourcePath := "/bigcatalogconfig/query_data/"
	result, err := core.Request[core.Record](ctx, b, http.MethodGet, resourcePath, params, nil)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// BigCatalogConfigQueryData_GET
// method: GET
// url: /bigcatalogconfig/query_data/
// summary: Queries data based on provided params
func (b *BigCatalogConfig) BigCatalogConfigQueryData_GET(params core.Params) (core.Record, error) {
	return b.BigCatalogConfigQueryDataWithContext_GET(b.Rest.GetCtx(), params)
}

// BigCatalogConfigQueryDataWithContext_POST
// method: POST
// url: /bigcatalogconfig/query_data/
// summary: Query VAST Catalog
func (b *BigCatalogConfig) BigCatalogConfigQueryDataWithContext_POST(ctx context.Context, body core.Params) (core.Record, error) {
	resourcePath := "/bigcatalogconfig/query_data/"
	result, err := core.Request[core.Record](ctx, b, http.MethodPost, resourcePath, nil, body)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// BigCatalogConfigQueryData_POST
// method: POST
// url: /bigcatalogconfig/query_data/
// summary: Query VAST Catalog
func (b *BigCatalogConfig) BigCatalogConfigQueryData_POST(body core.Params) (core.Record, error) {
	return b.BigCatalogConfigQueryDataWithContext_POST(b.Rest.GetCtx(), body)
}

// BigCatalogConfigStatsWithContext_GET
// method: GET
// url: /bigcatalogconfig/stats/
// summary: Return VAST Catalog Stats
func (b *BigCatalogConfig) BigCatalogConfigStatsWithContext_GET(ctx context.Context, params core.Params) (core.Record, error) {
	resourcePath := "/bigcatalogconfig/stats/"
	result, err := core.Request[core.Record](ctx, b, http.MethodGet, resourcePath, params, nil)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// BigCatalogConfigStats_GET
// method: GET
// url: /bigcatalogconfig/stats/
// summary: Return VAST Catalog Stats
func (b *BigCatalogConfig) BigCatalogConfigStats_GET(params core.Params) (core.Record, error) {
	return b.BigCatalogConfigStatsWithContext_GET(b.Rest.GetCtx(), params)
}
