// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"
	"time"

	"github.com/vast-data/go-vast-client/core"
)

// BlockHostMappingBulkWithContext_PATCH
// method: PATCH
// url: /blockmappings/bulk/
// summary: Map Block Hosts to Volumes
//
// Parameters:
//   - waitTimeout: If 0, returns immediately without waiting (async). Otherwise, waits for task completion with the specified timeout.
func (b *BlockHostMapping) BlockHostMappingBulkWithContext_PATCH(ctx context.Context, body core.Params, waitTimeout time.Duration) (*AsyncResult, error) {
	resourcePath := "/blockmappings/bulk/"
	result, err := core.Request[core.Record](ctx, b, http.MethodPatch, resourcePath, nil, body)
	if err != nil {
		return nil, err
	}

	return MaybeWaitAsyncResultWithContext(ctx, result, b.Rest, waitTimeout)

}

// BlockHostMappingBulk_PATCH
// method: PATCH
// url: /blockmappings/bulk/
// summary: Map Block Hosts to Volumes
//
// Parameters:
//   - waitTimeout: If 0, returns immediately without waiting (async). Otherwise, waits for task completion with the specified timeout.
func (b *BlockHostMapping) BlockHostMappingBulk_PATCH(body core.Params, waitTimeout time.Duration) (*AsyncResult, error) {
	return b.BlockHostMappingBulkWithContext_PATCH(b.Rest.GetCtx(), body, waitTimeout)
}
