// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the BlockHostMapping resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for BlockHostMapping extra methods
	// Resource path: blockhostvolumes

	core.RegisterExtraMethod(
		"BlockHostMapping",           // resource type (Go struct name)
		"BlockHostMappingBulk_PATCH", // method name
		"PATCH",                      // HTTP verb
		"/blockmappings/bulk/",       // URL path with placeholders
		"Map Block Hosts to Volumes", // summary from OpenAPI
	)

}
