// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the Cbox resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for Cbox extra methods
	// Resource path: cboxes

	core.RegisterExtraMethod(
		"Cbox",                      // resource type (Go struct name)
		"CboxControlLed_PATCH",      // method name
		"PATCH",                     // HTTP verb
		"/cboxes/{id}/control_led/", // URL path with placeholders
		"Control CBox LEDs",         // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"Cbox",                      // resource type (Go struct name)
		"CboxRefreshUid_PATCH",      // method name
		"PATCH",                     // HTTP verb
		"/cboxes/{id}/refresh_uid/", // URL path with placeholders
		"Refreshes cbox uid to match it's cnodes chassis serial", // summary from OpenAPI
	)

}
