// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the Certificate resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for Certificate extra methods
	// Resource path: certificates

	core.RegisterExtraMethod(
		"Certificate", // resource type (Go struct name)
		"CertificateValidateComputeClusterCertificates_POST", // method name
		"POST", // HTTP verb
		"/certificates/validate_compute_cluster_certificates/", // URL path with placeholders
		"Validate compute cluster RKE2 certificates",           // summary from OpenAPI
	)

}
