// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the Column resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for Column extra methods
	// Resource path: columns

	core.RegisterExtraMethod(
		"Column",                         // resource type (Go struct name)
		"ColumnDelete_DELETE",            // method name
		"DELETE",                         // HTTP verb
		"/columns/delete/",               // URL path with placeholders
		"Delete a Database Table Column", // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"Column",                         // resource type (Go struct name)
		"ColumnRename_PATCH",             // method name
		"PATCH",                          // HTTP verb
		"/columns/rename/",               // URL path with placeholders
		"Rename a Database Table Column", // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"Column",                       // resource type (Go struct name)
		"ColumnShow_GET",               // method name
		"GET",                          // HTTP verb
		"/columns/show/",               // URL path with placeholders
		"Show a Database Table Column", // summary from OpenAPI
	)

}
