// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// ConfigResetWithContext_POST
// method: POST
// url: /config/reset/
// summary: Reset all dynamic configs to their default values
func (c *Config) ConfigResetWithContext_POST(ctx context.Context, body core.Params) error {
	resourcePath := "/config/reset/"
	_, err := core.Request[core.EmptyRecord](ctx, c, http.MethodPost, resourcePath, nil, body)
	return err

}

// ConfigReset_POST
// method: POST
// url: /config/reset/
// summary: Reset all dynamic configs to their default values
func (c *Config) ConfigReset_POST(body core.Params) error {
	return c.ConfigResetWithContext_POST(c.Rest.GetCtx(), body)
}
