// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// EncryptionGroupDeactivateEncryptionGroupWithContext_POST
// method: POST
// url: /encryptiongroups/{id}/deactivate_encryption_group/
// summary: Deactivate encryption group.
//
// Body:
//
//	< not declared in schema >
func (e *EncryptionGroup) EncryptionGroupDeactivateEncryptionGroupWithContext_POST(ctx context.Context, id any, body core.Params) error {
	resourcePath := core.BuildResourcePathWithID("encryptiongroups", id, "deactivate_encryption_group")
	_, err := core.Request[core.Record](ctx, e, http.MethodPost, resourcePath, nil, body)
	return err

}

// EncryptionGroupDeactivateEncryptionGroup_POST
// method: POST
// url: /encryptiongroups/{id}/deactivate_encryption_group/
// summary: Deactivate encryption group.
//
// Body:
//
//	< not declared in schema >
func (e *EncryptionGroup) EncryptionGroupDeactivateEncryptionGroup_POST(id any, body core.Params) error {
	return e.EncryptionGroupDeactivateEncryptionGroupWithContext_POST(e.Rest.GetCtx(), id, body)
}

// EncryptionGroupReinstateEncryptionGroupWithContext_POST
// method: POST
// url: /encryptiongroups/{id}/reinstate_encryption_group/
// summary: Reinstate Encryption Group
//
// Body:
//
//	< not declared in schema >
func (e *EncryptionGroup) EncryptionGroupReinstateEncryptionGroupWithContext_POST(ctx context.Context, id any, body core.Params) error {
	resourcePath := core.BuildResourcePathWithID("encryptiongroups", id, "reinstate_encryption_group")
	_, err := core.Request[core.Record](ctx, e, http.MethodPost, resourcePath, nil, body)
	return err

}

// EncryptionGroupReinstateEncryptionGroup_POST
// method: POST
// url: /encryptiongroups/{id}/reinstate_encryption_group/
// summary: Reinstate Encryption Group
//
// Body:
//
//	< not declared in schema >
func (e *EncryptionGroup) EncryptionGroupReinstateEncryptionGroup_POST(id any, body core.Params) error {
	return e.EncryptionGroupReinstateEncryptionGroupWithContext_POST(e.Rest.GetCtx(), id, body)
}

// EncryptionGroupRevokeEncryptionGroupWithContext_POST
// method: POST
// url: /encryptiongroups/{id}/revoke_encryption_group/
// summary: Revoke Encryption Group
//
// Body:
//
//	< not declared in schema >
func (e *EncryptionGroup) EncryptionGroupRevokeEncryptionGroupWithContext_POST(ctx context.Context, id any, body core.Params) error {
	resourcePath := core.BuildResourcePathWithID("encryptiongroups", id, "revoke_encryption_group")
	_, err := core.Request[core.Record](ctx, e, http.MethodPost, resourcePath, nil, body)
	return err

}

// EncryptionGroupRevokeEncryptionGroup_POST
// method: POST
// url: /encryptiongroups/{id}/revoke_encryption_group/
// summary: Revoke Encryption Group
//
// Body:
//
//	< not declared in schema >
func (e *EncryptionGroup) EncryptionGroupRevokeEncryptionGroup_POST(id any, body core.Params) error {
	return e.EncryptionGroupRevokeEncryptionGroupWithContext_POST(e.Rest.GetCtx(), id, body)
}

// EncryptionGroupRotateEncryptionGroupKeyWithContext_POST
// method: POST
// url: /encryptiongroups/{id}/rotate_encryption_group_key/
// summary: Rotate Encryption Group Key
//
// Body:
//
//	< not declared in schema >
func (e *EncryptionGroup) EncryptionGroupRotateEncryptionGroupKeyWithContext_POST(ctx context.Context, id any, body core.Params) error {
	resourcePath := core.BuildResourcePathWithID("encryptiongroups", id, "rotate_encryption_group_key")
	_, err := core.Request[core.Record](ctx, e, http.MethodPost, resourcePath, nil, body)
	return err

}

// EncryptionGroupRotateEncryptionGroupKey_POST
// method: POST
// url: /encryptiongroups/{id}/rotate_encryption_group_key/
// summary: Rotate Encryption Group Key
//
// Body:
//
//	< not declared in schema >
func (e *EncryptionGroup) EncryptionGroupRotateEncryptionGroupKey_POST(id any, body core.Params) error {
	return e.EncryptionGroupRotateEncryptionGroupKeyWithContext_POST(e.Rest.GetCtx(), id, body)
}
