// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// EventBrokerListTopicsWithContext_GET
// method: GET
// url: /eventbrokers/{id}/list_topics/
// summary: Retrieve Kafka topics for the specified broker
//
// Params:
//   - topic_name_filter
func (e *EventBroker) EventBrokerListTopicsWithContext_GET(ctx context.Context, id any, params core.Params) (core.Record, error) {
	resourcePath := core.BuildResourcePathWithID("eventbrokers", id, "list_topics")
	result, err := core.Request[core.Record](ctx, e, http.MethodGet, resourcePath, params, nil)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// EventBrokerListTopics_GET
// method: GET
// url: /eventbrokers/{id}/list_topics/
// summary: Retrieve Kafka topics for the specified broker
//
// Params:
//   - topic_name_filter
func (e *EventBroker) EventBrokerListTopics_GET(id any, params core.Params) (core.Record, error) {
	return e.EventBrokerListTopicsWithContext_GET(e.Rest.GetCtx(), id, params)
}
