// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"
	"time"

	"github.com/vast-data/go-vast-client/core"
)

// EventDefinitionTestWithContext_PATCH
// method: PATCH
// url: /eventdefinitions/{id}/test/
// summary: Test Event Definition
//
// Body:
//
//	< not declared in schema >
//
// Parameters:
//   - waitTimeout: If 0, returns immediately without waiting (async). Otherwise, waits for task completion with the specified timeout.
func (e *EventDefinition) EventDefinitionTestWithContext_PATCH(ctx context.Context, id any, body core.Params, waitTimeout time.Duration) (*AsyncResult, error) {
	resourcePath := core.BuildResourcePathWithID("eventdefinitions", id, "test")
	result, err := core.Request[core.Record](ctx, e, http.MethodPatch, resourcePath, nil, body)
	if err != nil {
		return nil, err
	}

	return MaybeWaitAsyncResultWithContext(ctx, result, e.Rest, waitTimeout)

}

// EventDefinitionTest_PATCH
// method: PATCH
// url: /eventdefinitions/{id}/test/
// summary: Test Event Definition
//
// Body:
//
//	< not declared in schema >
//
// Parameters:
//   - waitTimeout: If 0, returns immediately without waiting (async). Otherwise, waits for task completion with the specified timeout.
func (e *EventDefinition) EventDefinitionTest_PATCH(id any, body core.Params, waitTimeout time.Duration) (*AsyncResult, error) {
	return e.EventDefinitionTestWithContext_PATCH(e.Rest.GetCtx(), id, body, waitTimeout)
}
