// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the EventBroker resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for EventBroker extra methods
	// Resource path: eventbrokers

	core.RegisterExtraMethod(
		"EventBroker",                     // resource type (Go struct name)
		"EventBrokerListTopics_GET",       // method name
		"GET",                             // HTTP verb
		"/eventbrokers/{id}/list_topics/", // URL path with placeholders
		"Retrieve Kafka topics for the specified broker", // summary from OpenAPI
	)

}
