// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the GlobalSnapshotStream resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for GlobalSnapshotStream extra methods
	// Resource path: globalsnapstreams

	core.RegisterExtraMethod(
		"GlobalSnapshotStream",            // resource type (Go struct name)
		"GlobalSnapshotStreamPause_PATCH", // method name
		"PATCH",                           // HTTP verb
		"/globalsnapstreams/{id}/pause/",  // URL path with placeholders
		"Pause a Global Snapshot Stream",  // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"GlobalSnapshotStream",             // resource type (Go struct name)
		"GlobalSnapshotStreamResume_PATCH", // method name
		"PATCH",                            // HTTP verb
		"/globalsnapstreams/{id}/resume/",  // URL path with placeholders
		"Resume a Global Snapshot Stream",  // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"GlobalSnapshotStream",           // resource type (Go struct name)
		"GlobalSnapshotStreamStop_PATCH", // method name
		"PATCH",                          // HTTP verb
		"/globalsnapstreams/{id}/stop/",  // URL path with placeholders
		"Stop a Global Snapshot Stream",  // summary from OpenAPI
	)

}
