// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the Group resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for Group extra methods
	// Resource path: groups

	core.RegisterExtraMethod(
		"Group",          // resource type (Go struct name)
		"GroupNames_GET", // method name
		"GET",            // HTTP verb
		"/groups/names/", // URL path with placeholders
		"Find Group by prefix and domain details", // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"Group",          // resource type (Go struct name)
		"GroupQuery_GET", // method name
		"GET",            // HTTP verb
		"/groups/query/", // URL path with placeholders
		"Query Group",    // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"Group",                  // resource type (Go struct name)
		"GroupQuery_PATCH",       // method name
		"PATCH",                  // HTTP verb
		"/groups/query/",         // URL path with placeholders
		"Modify non-Local Group", // summary from OpenAPI
	)

}
