// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// LdapSetPosixPrimaryWithContext_PATCH
// method: PATCH
// url: /ldaps/{id}/set_posix_primary/
// summary: Set LDAP as POSIX Primary Provider
func (l *Ldap) LdapSetPosixPrimaryWithContext_PATCH(ctx context.Context, id any, body core.Params) error {
	resourcePath := core.BuildResourcePathWithID("ldaps", id, "set_posix_primary")
	_, err := core.Request[core.Record](ctx, l, http.MethodPatch, resourcePath, nil, body)
	return err

}

// LdapSetPosixPrimary_PATCH
// method: PATCH
// url: /ldaps/{id}/set_posix_primary/
// summary: Set LDAP as POSIX Primary Provider
func (l *Ldap) LdapSetPosixPrimary_PATCH(id any, body core.Params) error {
	return l.LdapSetPosixPrimaryWithContext_PATCH(l.Rest.GetCtx(), id, body)
}
