// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// OidcRefreshKeysWithContext_PATCH
// method: PATCH
// url: /oidcs/{id}/refresh_keys/
// summary: Refresh the keys from OIDC provider
func (o *Oidc) OidcRefreshKeysWithContext_PATCH(ctx context.Context, id any, body core.Params) (core.Record, error) {
	resourcePath := core.BuildResourcePathWithID("oidcs", id, "refresh_keys")
	result, err := core.Request[core.Record](ctx, o, http.MethodPatch, resourcePath, nil, body)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// OidcRefreshKeys_PATCH
// method: PATCH
// url: /oidcs/{id}/refresh_keys/
// summary: Refresh the keys from OIDC provider
func (o *Oidc) OidcRefreshKeys_PATCH(id any, body core.Params) (core.Record, error) {
	return o.OidcRefreshKeysWithContext_PATCH(o.Rest.GetCtx(), id, body)
}
