// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the ProjectionColumn resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for ProjectionColumn extra methods
	// Resource path: projectioncolumns

	core.RegisterExtraMethod(
		"ProjectionColumn",         // resource type (Go struct name)
		"ProjectionColumnShow_GET", // method name
		"GET",                      // HTTP verb
		"/projectioncolumns/show/", // URL path with placeholders
		"Return a Database Table Semi-Sorted Projection Column", // summary from OpenAPI
	)

}
