// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"
	"time"

	"github.com/vast-data/go-vast-client/core"
)

// QuotaGroupAssignQuotasWithContext_PATCH
// method: PATCH
// url: /quotagroups/{id}/assign_quotas/
// summary: Assign quotas to quota group
//
// Body:
//   - quotas_ids: Quotas IDs
//
// Parameters:
//   - waitTimeout: If 0, returns immediately without waiting (async). Otherwise, waits for task completion with the specified timeout.
func (q *QuotaGroup) QuotaGroupAssignQuotasWithContext_PATCH(ctx context.Context, id any, body core.Params, waitTimeout time.Duration) (*AsyncResult, error) {
	resourcePath := core.BuildResourcePathWithID("quotagroups", id, "assign_quotas")
	result, err := core.Request[core.Record](ctx, q, http.MethodPatch, resourcePath, nil, body)
	if err != nil {
		return nil, err
	}

	return MaybeWaitAsyncResultWithContext(ctx, result, q.Rest, waitTimeout)

}

// QuotaGroupAssignQuotas_PATCH
// method: PATCH
// url: /quotagroups/{id}/assign_quotas/
// summary: Assign quotas to quota group
//
// Body:
//   - quotas_ids: Quotas IDs
//
// Parameters:
//   - waitTimeout: If 0, returns immediately without waiting (async). Otherwise, waits for task completion with the specified timeout.
func (q *QuotaGroup) QuotaGroupAssignQuotas_PATCH(id any, body core.Params, waitTimeout time.Duration) (*AsyncResult, error) {
	return q.QuotaGroupAssignQuotasWithContext_PATCH(q.Rest.GetCtx(), id, body, waitTimeout)
}

// QuotaGroupRefreshUserQuotasWithContext_PATCH
// method: PATCH
// url: /quotagroups/{id}/refresh_user_quotas/
// summary: Refresh user quotas of a quota group
//
// Body:
//
//	< not declared in schema >
func (q *QuotaGroup) QuotaGroupRefreshUserQuotasWithContext_PATCH(ctx context.Context, id any, body core.Params) error {
	resourcePath := core.BuildResourcePathWithID("quotagroups", id, "refresh_user_quotas")
	_, err := core.Request[core.Record](ctx, q, http.MethodPatch, resourcePath, nil, body)
	return err

}

// QuotaGroupRefreshUserQuotas_PATCH
// method: PATCH
// url: /quotagroups/{id}/refresh_user_quotas/
// summary: Refresh user quotas of a quota group
//
// Body:
//
//	< not declared in schema >
func (q *QuotaGroup) QuotaGroupRefreshUserQuotas_PATCH(id any, body core.Params) error {
	return q.QuotaGroupRefreshUserQuotasWithContext_PATCH(q.Rest.GetCtx(), id, body)
}

// QuotaGroupResetGracePeriodWithContext_PATCH
// method: PATCH
// url: /quotagroups/{id}/reset_grace_period/
// summary: Reset the grace period countdown after soft limit is exceeded
//
// Body:
//
//	< not declared in schema >
func (q *QuotaGroup) QuotaGroupResetGracePeriodWithContext_PATCH(ctx context.Context, id any, body core.Params) error {
	resourcePath := core.BuildResourcePathWithID("quotagroups", id, "reset_grace_period")
	_, err := core.Request[core.Record](ctx, q, http.MethodPatch, resourcePath, nil, body)
	return err

}

// QuotaGroupResetGracePeriod_PATCH
// method: PATCH
// url: /quotagroups/{id}/reset_grace_period/
// summary: Reset the grace period countdown after soft limit is exceeded
//
// Body:
//
//	< not declared in schema >
func (q *QuotaGroup) QuotaGroupResetGracePeriod_PATCH(id any, body core.Params) error {
	return q.QuotaGroupResetGracePeriodWithContext_PATCH(q.Rest.GetCtx(), id, body)
}
