// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the Rack resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for Rack extra methods
	// Resource path: racks

	core.RegisterExtraMethod(
		"Rack",                   // resource type (Go struct name)
		"RackAddBoxes_POST",      // method name
		"POST",                   // HTTP verb
		"/racks/{id}/add_boxes/", // URL path with placeholders
		"Add Boxes to a Rack",    // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"Rack",                   // resource type (Go struct name)
		"RackBgpconfig_POST",     // method name
		"POST",                   // HTTP verb
		"/racks/{id}/bgpconfig/", // URL path with placeholders
		"Configure BGP on Rack",  // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"Rack",                     // resource type (Go struct name)
		"RackControlLed_PATCH",     // method name
		"PATCH",                    // HTTP verb
		"/racks/{id}/control_led/", // URL path with placeholders
		"Control Rack Boxes LED",   // summary from OpenAPI
	)

	core.RegisterExtraMethod(
		"Rack",                // resource type (Go struct name)
		"RackRename_PATCH",    // method name
		"PATCH",               // HTTP verb
		"/racks/{id}/rename/", // URL path with placeholders
		"Rename Rack",         // summary from OpenAPI
	)

}
