// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// ReplicationPeersGetRemoteMappingWithContext_GET
// method: GET
// url: /nativereplicationremotetargets/get_remote_mapping/
// summary: Get the mapping between replication peers and remote view policies
func (r *ReplicationPeers) ReplicationPeersGetRemoteMappingWithContext_GET(ctx context.Context) (core.Record, error) {
	resourcePath := "/nativereplicationremotetargets/get_remote_mapping/"
	result, err := core.Request[core.Record](ctx, r, http.MethodGet, resourcePath, nil, nil)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ReplicationPeersGetRemoteMapping_GET
// method: GET
// url: /nativereplicationremotetargets/get_remote_mapping/
// summary: Get the mapping between replication peers and remote view policies
func (r *ReplicationPeers) ReplicationPeersGetRemoteMapping_GET() (core.Record, error) {
	return r.ReplicationPeersGetRemoteMappingWithContext_GET(r.Rest.GetCtx())
}
