// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the ReplicationPeers resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for ReplicationPeers extra methods
	// Resource path: nativereplicationremotetargets

	core.RegisterExtraMethod(
		"ReplicationPeers",                     // resource type (Go struct name)
		"ReplicationPeersGetRemoteMapping_GET", // method name
		"GET",                                  // HTTP verb
		"/nativereplicationremotetargets/get_remote_mapping/",                // URL path with placeholders
		"Get the mapping between replication peers and remote view policies", // summary from OpenAPI
	)

}
