// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the S3LifeCycleRule resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for S3LifeCycleRule extra methods
	// Resource path: s3lifecyclerules

	core.RegisterExtraMethod(
		"S3LifeCycleRule",                        // resource type (Go struct name)
		"S3LifeCycleRuleGetObjectExpiration_GET", // method name
		"GET",                                    // HTTP verb
		"/s3lifecyclerules/get_object_expiration/", // URL path with placeholders
		"Get Object Expiration Information",        // summary from OpenAPI
	)

}
