// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// S3LifeCycleRuleGetObjectExpirationWithContext_GET
// method: GET
// url: /s3lifecyclerules/get_object_expiration/
// summary: Get Object Expiration Information
//
// Params:
//   - object_name: Object name
//   - bucket_name: Bucket name
func (s *S3LifeCycleRule) S3LifeCycleRuleGetObjectExpirationWithContext_GET(ctx context.Context, params core.Params) (core.Record, error) {
	resourcePath := "/s3lifecyclerules/get_object_expiration/"
	result, err := core.Request[core.Record](ctx, s, http.MethodGet, resourcePath, params, nil)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// S3LifeCycleRuleGetObjectExpiration_GET
// method: GET
// url: /s3lifecyclerules/get_object_expiration/
// summary: Get Object Expiration Information
//
// Params:
//   - object_name: Object name
//   - bucket_name: Bucket name
func (s *S3LifeCycleRule) S3LifeCycleRuleGetObjectExpiration_GET(params core.Params) (core.Record, error) {
	return s.S3LifeCycleRuleGetObjectExpirationWithContext_GET(s.Rest.GetCtx(), params)
}
