// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// SchemaDeleteWithContext_DELETE
// method: DELETE
// url: /schemas/delete/
// summary: Delete Schema
//
// Body:
//   - database_name: Name of the Database
//   - name: Name of the object
//   - tenant_id: Tenant ID
func (s *Schema) SchemaDeleteWithContext_DELETE(ctx context.Context, body core.Params) error {
	resourcePath := "/schemas/delete/"
	_, err := core.Request[core.Record](ctx, s, http.MethodDelete, resourcePath, nil, body)
	return err

}

// SchemaDelete_DELETE
// method: DELETE
// url: /schemas/delete/
// summary: Delete Schema
//
// Body:
//   - database_name: Name of the Database
//   - name: Name of the object
//   - tenant_id: Tenant ID
func (s *Schema) SchemaDelete_DELETE(body core.Params) error {
	return s.SchemaDeleteWithContext_DELETE(s.Rest.GetCtx(), body)
}

// SchemaRenameWithContext_PATCH
// method: PATCH
// url: /schemas/rename/
// summary: Rename a database schema
//
// Body:
//   - database_name: Name of the Database
//   - name: Name of the object
//   - new_name: New name of the Schema
//   - new_schema_name: New name of the Schema (deprecated since 5.0)
//   - tenant_id: Tenant ID
func (s *Schema) SchemaRenameWithContext_PATCH(ctx context.Context, body core.Params) error {
	resourcePath := "/schemas/rename/"
	_, err := core.Request[core.Record](ctx, s, http.MethodPatch, resourcePath, nil, body)
	return err

}

// SchemaRename_PATCH
// method: PATCH
// url: /schemas/rename/
// summary: Rename a database schema
//
// Body:
//   - database_name: Name of the Database
//   - name: Name of the object
//   - new_name: New name of the Schema
//   - new_schema_name: New name of the Schema (deprecated since 5.0)
//   - tenant_id: Tenant ID
func (s *Schema) SchemaRename_PATCH(body core.Params) error {
	return s.SchemaRenameWithContext_PATCH(s.Rest.GetCtx(), body)
}

// SchemaShowWithContext_GET
// method: GET
// url: /schemas/show/
// summary: Show a Database Schema
//
// Params:
//   - tenant_id: Filter by tenant. Specify tenant ID.
//   - database_name: Getting list of objects by database_name
//   - name: Getting object by exact match
func (s *Schema) SchemaShowWithContext_GET(ctx context.Context, params core.Params) (core.Record, error) {
	resourcePath := "/schemas/show/"
	result, err := core.Request[core.Record](ctx, s, http.MethodGet, resourcePath, params, nil)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// SchemaShow_GET
// method: GET
// url: /schemas/show/
// summary: Show a Database Schema
//
// Params:
//   - tenant_id: Filter by tenant. Specify tenant ID.
//   - database_name: Getting list of objects by database_name
//   - name: Getting object by exact match
func (s *Schema) SchemaShow_GET(params core.Params) (core.Record, error) {
	return s.SchemaShowWithContext_GET(s.Rest.GetCtx(), params)
}
