// Code generated by generate-untyped-resources. DO NOT EDIT.

package untyped

import "github.com/vast-data/go-vast-client/core"

// This file registers metadata for all extra methods on the VastdbTable resource
// This information comes from the OpenAPI schema during code generation

func init() {
	// Register metadata for VastdbTable extra methods
	// Resource path: vastdbtable

	core.RegisterExtraMethod(
		"VastdbTable",                          // resource type (Go struct name)
		"VastdbTableAggregate_GET",             // method name
		"GET",                                  // HTTP verb
		"/vastdbtable/aggregate/",              // URL path with placeholders
		"Shows historical data for the table.", // summary from OpenAPI
	)

}
