// Code generated by generate-typed-resources. DO NOT EDIT.
// Template: LIST|READ

package typed

import (
	"context"

	"github.com/vast-data/go-vast-client/core"
)

// -----------------------------------------------------
// RESOURCE TYPE
// -----------------------------------------------------

// Port represents a typed resource for port operations
type Port struct {
	*core.TypedVastResource
}

// -----------------------------------------------------
// SEARCH PARAMS
// -----------------------------------------------------

// PortSearchParams represents the search parameters for Port operations
type PortSearchParams struct {
	Guid  string `json:"guid,omitempty" yaml:"guid,omitempty" required:"false" doc:""`
	Model string `json:"model,omitempty" yaml:"model,omitempty" required:"false" doc:"Filter by port model"`
	Name  string `json:"name,omitempty" yaml:"name,omitempty" required:"false" doc:""`
	State string `json:"state,omitempty" yaml:"state,omitempty" required:"false" doc:"Filter by port state"`

	// RawData allows passing arbitrary search parameters as key-value pairs.
	//
	// Use this field when you need query parameters that are not covered by the typed fields above.
	// This is particularly useful for:
	//   - Dynamic filter operations (e.g., "path__contains", "name__icontains")
	//   - Django-style query filters
	//   - Custom backend-specific parameters
	//
	// Example:
	//   params := &PortSearchParams{
	//       RawData: core.Params{"path__contains": "/foo", "name__icontains": "bar"},
	//   }
	//
	// Note: You can use either the typed fields or RawData, or combine both.
	RawData core.Params `json:"-" yaml:"-"`
}

// -----------------------------------------------------
// MODELS
// -----------------------------------------------------

// PortDetailsModel represents the detailed model returned by GET/List operations
// Type alias to component definition: #/components/schemas/Port
type PortDetailsModel = Component_Port

// -----------------------------------------------------
// LIST
// -----------------------------------------------------

// List retrieves multiple ports with typed request/response
// summary: List Switch Ports
func (r *Port) List(req *PortSearchParams) ([]*PortDetailsModel, error) {
	return r.ListWithContext(r.Untyped.GetCtx(), req)
}

// ListWithContext retrieves multiple ports with typed request/response using provided context
// summary: List Switch Ports
func (r *Port) ListWithContext(ctx context.Context, req *PortSearchParams) ([]*PortDetailsModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	recordSet, err := r.Untyped.GetResourceMap()[r.GetResourceType()].ListWithContext(ctx, params)
	if err != nil {
		return nil, err
	}

	var response []*PortDetailsModel
	if err := recordSet.Fill(&response); err != nil {
		return nil, err
	}

	return response, nil
}

// Get retrieves a single port with typed request/response
// summary: List Switch Ports
func (r *Port) Get(req *PortSearchParams) (*PortDetailsModel, error) {
	return r.GetWithContext(r.Untyped.GetCtx(), req)
}

// GetWithContext retrieves a single port with typed request/response using provided context
// summary: List Switch Ports
func (r *Port) GetWithContext(ctx context.Context, req *PortSearchParams) (*PortDetailsModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].GetWithContext(ctx, params)
	if err != nil {
		return nil, err
	}

	var response PortDetailsModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// -----------------------------------------------------
// READ
// -----------------------------------------------------

// GetById retrieves a single port by ID
// summary: Return Details of One Switch Port
func (r *Port) GetById(id any) (*PortDetailsModel, error) {
	return r.GetByIdWithContext(r.Untyped.GetCtx(), id)
}

// GetByIdWithContext retrieves a single port by ID using provided context
// summary: Return Details of One Switch Port
func (r *Port) GetByIdWithContext(ctx context.Context, id any) (*PortDetailsModel, error) {
	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].GetByIdWithContext(ctx, id)
	if err != nil {
		return nil, err
	}

	var response PortDetailsModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// Exists checks if a port exists
func (r *Port) Exists(req *PortSearchParams) (bool, error) {
	return r.ExistsWithContext(r.Untyped.GetCtx(), req)
}

// ExistsWithContext checks if a port exists using provided context
func (r *Port) ExistsWithContext(ctx context.Context, req *PortSearchParams) (bool, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return false, err
	}
	return r.Untyped.GetResourceMap()[r.GetResourceType()].ExistsWithContext(ctx, params)
}

// MustExists checks if a port exists and panics if not
func (r *Port) MustExists(req *PortSearchParams) bool {
	return r.MustExistsWithContext(r.Untyped.GetCtx(), req)
}

// MustExistsWithContext checks if a port exists and panics if not using provided context
func (r *Port) MustExistsWithContext(ctx context.Context, req *PortSearchParams) bool {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		panic(err)
	}
	return r.Untyped.GetResourceMap()[r.GetResourceType()].MustExistsWithContext(ctx, params)
}
