// Code generated by generate-typed-resources. DO NOT EDIT.
// Template: LIST

package typed

import (
	"context"
	"net/http"

	"github.com/vast-data/go-vast-client/core"
)

// -----------------------------------------------------
// RESOURCE TYPE
// -----------------------------------------------------

// SupportBundlesQueue represents a typed resource for supportbundlesqueue operations
type SupportBundlesQueue struct {
	*core.TypedVastResource
}

// -----------------------------------------------------
// SEARCH PARAMS
// -----------------------------------------------------

// SupportBundlesQueueSearchParams represents the search parameters for SupportBundlesQueue operations
type SupportBundlesQueueSearchParams struct {

	// RawData allows passing arbitrary search parameters as key-value pairs.
	//
	// Use this field when you need query parameters that are not covered by the typed fields above.
	// This is particularly useful for:
	//   - Dynamic filter operations (e.g., "path__contains", "name__icontains")
	//   - Django-style query filters
	//   - Custom backend-specific parameters
	//
	// Example:
	//   params := &SupportBundlesQueueSearchParams{
	//       RawData: core.Params{"path__contains": "/foo", "name__icontains": "bar"},
	//   }
	//
	// Note: You can use either the typed fields or RawData, or combine both.
	RawData core.Params `json:"-" yaml:"-"`
}

// -----------------------------------------------------
// MODELS
// -----------------------------------------------------

// SupportBundlesQueueDetailsModel represents the detailed model returned by GET/List operations
// Type alias to component definition: #/components/schemas/SupportBundle
type SupportBundlesQueueDetailsModel = Component_SupportBundle

// -----------------------------------------------------
// LIST
// -----------------------------------------------------

// List retrieves multiple supportbundlesqueues with typed request/response
// summary: List queued supportbundles
func (r *SupportBundlesQueue) List(req *SupportBundlesQueueSearchParams) ([]*SupportBundlesQueueDetailsModel, error) {
	return r.ListWithContext(r.Untyped.GetCtx(), req)
}

// ListWithContext retrieves multiple supportbundlesqueues with typed request/response using provided context
// summary: List queued supportbundles
func (r *SupportBundlesQueue) ListWithContext(ctx context.Context, req *SupportBundlesQueueSearchParams) ([]*SupportBundlesQueueDetailsModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	recordSet, err := r.Untyped.GetResourceMap()[r.GetResourceType()].ListWithContext(ctx, params)
	if err != nil {
		return nil, err
	}

	var response []*SupportBundlesQueueDetailsModel
	if err := recordSet.Fill(&response); err != nil {
		return nil, err
	}

	return response, nil
}

// Get retrieves a single supportbundlesqueue with typed request/response
// summary: List queued supportbundles
func (r *SupportBundlesQueue) Get(req *SupportBundlesQueueSearchParams) (*SupportBundlesQueueDetailsModel, error) {
	return r.GetWithContext(r.Untyped.GetCtx(), req)
}

// GetWithContext retrieves a single supportbundlesqueue with typed request/response using provided context
// summary: List queued supportbundles
func (r *SupportBundlesQueue) GetWithContext(ctx context.Context, req *SupportBundlesQueueSearchParams) (*SupportBundlesQueueDetailsModel, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return nil, err
	}

	record, err := r.Untyped.GetResourceMap()[r.GetResourceType()].GetWithContext(ctx, params)
	if err != nil {
		return nil, err
	}

	var response SupportBundlesQueueDetailsModel
	if err := record.Fill(&response); err != nil {
		return nil, err
	}

	return &response, nil
}

// Exists checks if a supportbundlesqueue exists
func (r *SupportBundlesQueue) Exists(req *SupportBundlesQueueSearchParams) (bool, error) {
	return r.ExistsWithContext(r.Untyped.GetCtx(), req)
}

// ExistsWithContext checks if a supportbundlesqueue exists using provided context
func (r *SupportBundlesQueue) ExistsWithContext(ctx context.Context, req *SupportBundlesQueueSearchParams) (bool, error) {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		return false, err
	}
	return r.Untyped.GetResourceMap()[r.GetResourceType()].ExistsWithContext(ctx, params)
}

// MustExists checks if a supportbundlesqueue exists and panics if not
func (r *SupportBundlesQueue) MustExists(req *SupportBundlesQueueSearchParams) bool {
	return r.MustExistsWithContext(r.Untyped.GetCtx(), req)
}

// MustExistsWithContext checks if a supportbundlesqueue exists and panics if not using provided context
func (r *SupportBundlesQueue) MustExistsWithContext(ctx context.Context, req *SupportBundlesQueueSearchParams) bool {
	params, err := core.NewParamsFromStruct(req)
	if err != nil {
		panic(err)
	}
	return r.Untyped.GetResourceMap()[r.GetResourceType()].MustExistsWithContext(ctx, params)
}

// -----------------------------------------------------
// EXTRA METHODS
// -----------------------------------------------------

// SupportBundlesQueueMove_PATCH_Model represents the response model for SupportBundlesQueueMove
type SupportBundlesQueueMove_PATCH_Model struct {
	AccessKey       string   `json:"access_key,omitempty" yaml:"access_key,omitempty" required:"false" doc:"S3 Bucket access key"`
	Aggregated      bool     `json:"aggregated,omitempty" yaml:"aggregated,omitempty" required:"false" doc:"Aggregate harvests into final bundle (deprecated)"`
	AstronArgs      string   `json:"astron_args,omitempty" yaml:"astron_args,omitempty" required:"false" doc:""`
	BucketName      string   `json:"bucket_name,omitempty" yaml:"bucket_name,omitempty" required:"false" doc:"S3 Bucket for upload"`
	BucketSubdir    string   `json:"bucket_subdir,omitempty" yaml:"bucket_subdir,omitempty" required:"false" doc:"Sub-directory in support bucket"`
	BundleFile      string   `json:"bundle_file,omitempty" yaml:"bundle_file,omitempty" required:"false" doc:""`
	BundleSize      int64    `json:"bundle_size,omitempty" yaml:"bundle_size,omitempty" required:"false" doc:"Bundle size in bytes"`
	BundleUrl       string   `json:"bundle_url,omitempty" yaml:"bundle_url,omitempty" required:"false" doc:"URL to access/download support bundle file"`
	Callhome        bool     `json:"callhome,omitempty" yaml:"callhome,omitempty" required:"false" doc:""`
	Cluster         string   `json:"cluster,omitempty" yaml:"cluster,omitempty" required:"false" doc:"Parent Cluster"`
	ClusterId       int64    `json:"cluster_id,omitempty" yaml:"cluster_id,omitempty" required:"false" doc:""`
	CnodeIds        *[]int64 `json:"cnode_ids,omitempty" yaml:"cnode_ids,omitempty" required:"false" doc:"Array of IDs of specific CNodes from which logs are collected. If not specified, logs are collected from all CNodes."`
	CnodeIdsArray   *[]int64 `json:"cnode_ids_array,omitempty" yaml:"cnode_ids_array,omitempty" required:"false" doc:"Resolved CNode IDs included in the bundle harvest"`
	CnodesOnly      bool     `json:"cnodes_only,omitempty" yaml:"cnodes_only,omitempty" required:"false" doc:""`
	Core            bool     `json:"core,omitempty" yaml:"core,omitempty" required:"false" doc:""`
	CreateDatetime  string   `json:"create_datetime,omitempty" yaml:"create_datetime,omitempty" required:"false" doc:""`
	Created         string   `json:"created,omitempty" yaml:"created,omitempty" required:"false" doc:"Bundle creation time"`
	DeleteAfterSend bool     `json:"delete_after_send,omitempty" yaml:"delete_after_send,omitempty" required:"false" doc:"Delete the bundle immediately after successfully uploading"`
	DnodeIds        *[]int64 `json:"dnode_ids,omitempty" yaml:"dnode_ids,omitempty" required:"false" doc:"Array of IDs of specific DNodes from which logs are collected. If not specified, logs are collected from all DNodes."`
	DnodeIdsArray   *[]int64 `json:"dnode_ids_array,omitempty" yaml:"dnode_ids_array,omitempty" required:"false" doc:"Resolved DNode IDs included in the bundle harvest"`
	DnodesOnly      bool     `json:"dnodes_only,omitempty" yaml:"dnodes_only,omitempty" required:"false" doc:""`
	EndTime         string   `json:"end_time,omitempty" yaml:"end_time,omitempty" required:"false" doc:"End time of logs in UTC+3"`
	Guid            string   `json:"guid,omitempty" yaml:"guid,omitempty" required:"false" doc:""`
	HubbleArgs      string   `json:"hubble_args,omitempty" yaml:"hubble_args,omitempty" required:"false" doc:""`
	Id              int64    `json:"id,omitempty" yaml:"id,omitempty" required:"false" doc:""`
	Level           string   `json:"level,omitempty" yaml:"level,omitempty" required:"false" doc:"Bundle level e.g. small, medium, large"`
	LunaArgs        string   `json:"luna_args,omitempty" yaml:"luna_args,omitempty" required:"false" doc:""`
	Management      bool     `json:"management,omitempty" yaml:"management,omitempty" required:"false" doc:""`
	MaxSize         float32  `json:"max_size,omitempty" yaml:"max_size,omitempty" required:"false" doc:"Trace files bundle size limit in GB for each node"`
	MemTraces       bool     `json:"mem_traces,omitempty" yaml:"mem_traces,omitempty" required:"false" doc:""`
	Metrics         bool     `json:"metrics,omitempty" yaml:"metrics,omitempty" required:"false" doc:""`
	Name            string   `json:"name,omitempty" yaml:"name,omitempty" required:"false" doc:""`
	Obfuscated      bool     `json:"obfuscated,omitempty" yaml:"obfuscated,omitempty" required:"false" doc:"True if the bundle is obfuscated. If obfuscated, all bundled objects are converted to text and obfuscated. Any data that cannot be converted to text is not included in the bundle. The following types of information are replaced with a non-reversible hash: file and directory names, IP addresses, host names, user names, passwords, MAC addresses."`
	OnNfs           bool     `json:"on_nfs,omitempty" yaml:"on_nfs,omitempty" required:"false" doc:"True if the bundle is stored on NFS"`
	Performance     bool     `json:"performance,omitempty" yaml:"performance,omitempty" required:"false" doc:""`
	Platform        bool     `json:"platform,omitempty" yaml:"platform,omitempty" required:"false" doc:""`
	PositionInQueue int64    `json:"position_in_queue,omitempty" yaml:"position_in_queue,omitempty" required:"false" doc:"Position of the support bundle in the queue"`
	Prefix          string   `json:"prefix,omitempty" yaml:"prefix,omitempty" required:"false" doc:"Identifying label included in the bundle file name as a prefix"`
	Preset          string   `json:"preset,omitempty" yaml:"preset,omitempty" required:"false" doc:"Type of predefined preset bundle"`
	SecretKey       string   `json:"secret_key,omitempty" yaml:"secret_key,omitempty" required:"false" doc:"S3 Bucket secret key"`
	SendNow         bool     `json:"send_now,omitempty" yaml:"send_now,omitempty" required:"false" doc:"Upload support bundle after creation"`
	StartTime       string   `json:"start_time,omitempty" yaml:"start_time,omitempty" required:"false" doc:"Start time of logs in UTC+3"`
	State           string   `json:"state,omitempty" yaml:"state,omitempty" required:"false" doc:"State of the bundle"`
	Text            bool     `json:"text,omitempty" yaml:"text,omitempty" required:"false" doc:"True if only textual logs are included in the bundle"`
	Traces          bool     `json:"traces,omitempty" yaml:"traces,omitempty" required:"false" doc:""`
	UploadViaVms    bool     `json:"upload_via_vms,omitempty" yaml:"upload_via_vms,omitempty" required:"false" doc:""`
	Url             string   `json:"url,omitempty" yaml:"url,omitempty" required:"false" doc:""`
	VolumeSize      int64    `json:"volume_size,omitempty" yaml:"volume_size,omitempty" required:"false" doc:""`
}

// SupportBundlesQueueMoveWithContext_PATCH
// method: PATCH
// url: /supportbundlesqueue/{id}/move/
// summary: Move Support Bundle to a new position in a queue
//
// Parameters:
//   - position (body): New Support Bundle position in a queue
func (r *SupportBundlesQueue) SupportBundlesQueueMoveWithContext_PATCH(ctx context.Context, id any, position int64) (*SupportBundlesQueueMove_PATCH_Model, error) {
	resourcePath := core.BuildResourcePathWithID("supportbundlesqueue", id, "move")

	var reqParams core.Params
	reqBody := core.Params{}
	reqBody["position"] = position

	record, err := core.Request[core.Record](ctx, r.Untyped.GetResourceMap()[r.GetResourceType()], http.MethodPatch, resourcePath, reqParams, reqBody)
	if err != nil {
		return nil, err
	}

	var response SupportBundlesQueueMove_PATCH_Model
	if err := record.Fill(&response); err != nil {
		return nil, err
	}
	return &response, nil

}

// SupportBundlesQueueMove_PATCH
// method: PATCH
// url: /supportbundlesqueue/{id}/move/
// summary: Move Support Bundle to a new position in a queue
//
// Parameters:
//   - position (body): New Support Bundle position in a queue
func (r *SupportBundlesQueue) SupportBundlesQueueMove_PATCH(id any, position int64) (*SupportBundlesQueueMove_PATCH_Model, error) {
	return r.SupportBundlesQueueMoveWithContext_PATCH(r.Untyped.GetCtx(), id, position)
}
