// Code generated by generate-typed-resources. DO NOT EDIT.
// Template: EMPTY (All methods skipped)

package typed

import (
	"github.com/vast-data/go-vast-client/core"
)

// VastdbTable provides typed access to VastdbTable operations
type VastdbTable struct {
	*core.TypedVastResource
}

// -----------------------------------------------------
// GENERATION ISSUES
// -----------------------------------------------------
//   - Extra method GET /vastdbtable/aggregate/ skipped: GET /vastdbtable/aggregate/ - Response is a map-like object (additionalProperties: object). Typed methods do not support map return types
